# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DEMtoVector
                                 A QGIS plugin
 The plugin allows you to get a DXF file with 3D dots using DEM for importing into third-party software.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-07-23
        copyright            : (C) 2025 by Semenova Arina, simesha
        email                : semenova.risha@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""
from qgis.core import QgsCoordinateTransform, QgsProject, QgsVectorLayer, QgsFeatureRequest, QgsVectorFileWriter, QgsProcessingFeedback, QgsCoordinateReferenceSystem, QgsRasterLayer, QgsApplication
from qgis.gui import QgsMapCanvas
from qgis.utils import iface
from qgis.PyQt.QtCore import QVariant, QFileInfo
import processing
import os
from .functions_DEM import *
import math

# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load DEMtoVector class from file DEMtoVector.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .dem_to_vector import DEMtoVector
    return DEMtoVector(iface)
