# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DEMtoVector
                                 A QGIS plugin
 The plugin allows you to get a DXF file with 3D dots using DEM for importing into third-party software.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-07-23
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Semenova Arina, simesha
        email                : semenova.risha@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .dem_to_vector_dialog import DEMtoVectorDialog
import os.path
from .functions_DEM import *
import math
from datetime import datetime

from qgis.core import QgsProject, QgsVectorLayer, QgsFeatureRequest, QgsVectorFileWriter, QgsProcessingFeedback, QgsCoordinateReferenceSystem, QgsRasterLayer, QgsApplication, QgsMapLayerProxyModel
from qgis.gui import QgsMapCanvas
from qgis.utils import iface
from qgis.PyQt.QtCore import QVariant, QFileInfo
from PyQt5.QtWidgets import QTextBrowser
import processing
import os
import math

class DEMtoVector:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        self.dem_to_vector_dialog = DEMtoVectorDialog()
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'DEMtoVector_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&DEM to vector (DXF)')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('DEMtoVector', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToWebMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = f'{self.plugin_dir}/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Creating 3D-dots using DEM'),
            callback=self.run,
            parent=self.iface.mainWindow())
        
        self.dem_to_vector_dialog.OkButton.accepted.connect(self.__load_data)
        self.dem_to_vector_dialog.OkButton.rejected.connect(self.rejected_close)
        self.dem_to_vector_dialog.SelectDEM.currentIndexChanged.connect(self.raster_dem)
        self.dem_to_vector_dialog.checkCrs.stateChanged.connect(self.crs_instal) #если ошибка, то stateChanged --> checkStateChanged
        self.dem_to_vector_dialog.radioButton_3.toggled.connect(self.border_flag)
        self.dem_to_vector_dialog.BorderLayer.setFilters(QgsMapLayerProxyModel.PolygonLayer)       


        # will be set False in run()
        self.first_start = True

    def __load_data(self):


        #crs = self.dem_to_vector_dialog.CoordSystem.crs() # ID системы координат
        expFolder = self.dem_to_vector_dialog.outputFile.filePath() # Путь к папке для сохранения

        radio_buttons = {
            1: self.dem_to_vector_dialog.radioButton_1, # 1 - обрезать растр по маске
            2: self.dem_to_vector_dialog.radioButton_2, # 2 - обрезать по охвату слоя
            3: self.dem_to_vector_dialog.radioButton_3  # 3 - обрезать по охвату карты
        }

        flag = next((key for key, rb in radio_buttons.items() if rb.isChecked()), 1)  # 3 - значение по умолчанию

        chek = self.dem_to_vector_dialog.LayersCheckBox.isChecked()
        crs = self.dem_to_vector_dialog.checkCrs.isChecked()

        if flag != 3:
            input_vector = self.dem_to_vector_dialog.BorderLayer.currentLayer()
        else:
            input_vector = create_extent_rectangle_layer(chek)

        raster_archive = self.dem_to_vector_dialog.SelectDEM.currentIndex()
        

        self.dem_to_vector_fun(input_vector, raster_archive, crs, expFolder, flag, chek)


    def rejected_close(self):
        self.dem_to_vector_dialog.close()
    
    def raster_dem(self,index):
        if index == 0:
            self.dem_to_vector_dialog.label_5.setEnabled(False)  # Отключаем
            self.dem_to_vector_dialog.RasterLayer.setEnabled(False)  # Отключаем
        elif index == 1:
            self.dem_to_vector_dialog.label_5.setEnabled(True)  
            self.dem_to_vector_dialog.RasterLayer.setEnabled(True)  
    
    def crs_instal(self):
        if self.dem_to_vector_dialog.checkCrs.isChecked():
            self.dem_to_vector_dialog.label_7.setEnabled(True)  # Отключаем
            self.dem_to_vector_dialog.CrsTextEdit.setEnabled(True)  # Отключаем
        else:
            self.dem_to_vector_dialog.label_7.setEnabled(False)  
            self.dem_to_vector_dialog.CrsTextEdit.setEnabled(False)  
    
    def border_flag(self):
        if self.dem_to_vector_dialog.radioButton_3.isChecked():
            self.dem_to_vector_dialog.label_3.setEnabled(False)  # ОтключаемaddMapLayer
            self.dem_to_vector_dialog.BorderLayer.setEnabled(False)  # Отключаем
        else:
            self.dem_to_vector_dialog.label_3.setEnabled(True)  
            self.dem_to_vector_dialog.BorderLayer.setEnabled(True) 

    def clean_memory(self):
        # Получаем все слои проекта (включая неотображаемые)
        all_layers = QgsProject.instance().mapLayers().values()

        # Удаляем слои с флагом "не отображать"
        for layer in all_layers:
            if not QgsProject.instance().layerTreeRoot().findLayer(layer):
                #print(f"Удаляем скрытый слой: {layer.name()}")
                QgsProject.instance().removeMapLayer(layer.id())



    def dem_to_vector_fun(self,input_vector, raster_archive, crs, expFolder, flag, chek):
        self.dem_to_vector_dialog.progressBar.setFormat('%p% Процесс запущен, началась загрузка карт высот')
        self.dem_to_vector_dialog.progressBar.setValue(0)
        try:

            #raster_archive_list = [r'O:\ОИГ\data\DEM\FABDEM', None]
            if raster_archive == 2:
                input_raster = self.dem_to_vector_dialog.RasterLayer.currentLayer()
            else:
                if self.dem_to_vector_dialog.directoryGet.filePath() == '':
                    raster_archive = r'O:\ОИГ\data\DEM\FABDEM'
                else:
                    raster_archive = self.dem_to_vector_dialog.directoryGet.filePath()
                input_raster = serch_raster(input_vector, raster_archive, flag, chek)

            #path_exp(expFolder) # Если указывалась папка сохранения
            self.dem_to_vector_dialog.progressBar.setFormat('%p% Объединение карт в одну')
            self.dem_to_vector_dialog.progressBar.setValue(20)

            input_raster = MergeRaster(input_raster, chek)

            if crs:
                crs_proj = QgsCoordinateReferenceSystem()
                set_crs = self.dem_to_vector_dialog.CrsTextEdit.toPlainText()
                crs_proj.createFromProj4(set_crs)
            else:
                crs_proj = self.dem_to_vector_dialog.CoordSystem.crs() # ID системы координат

            if crs_proj.isValid() == False:
                crs_proj = QgsCoordinateReferenceSystem("EPSG:4326")
            self.dem_to_vector_dialog.progressBar.setFormat('%p% Перепроецирование')
            self.dem_to_vector_dialog.progressBar.setValue(30)


            input_raster = warpreproject(input_raster,crs_proj, chek)

            #if flag != 3:
            if type(input_vector) is str:
                vector_crs = QgsVectorLayer(input_vector).crs()
            else:
                vector_crs = input_vector.crs()

            if crs_proj != vector_crs:
                input_vector = ReprojectLayer(input_vector,crs_proj,chek)
            self.dem_to_vector_dialog.progressBar.setFormat('%p% Обрезка')
            self.dem_to_vector_dialog.progressBar.setValue(40)


            input_raster = clip_raster(input_raster, input_vector, flag, chek)
            self.dem_to_vector_dialog.progressBar.setFormat('%p% Создание вершин в пикселях')
            self.dem_to_vector_dialog.progressBar.setValue(50)
            input_vector = pixels_to_points(input_raster, chek)
            self.dem_to_vector_dialog.progressBar.setFormat('%p% Добавление атрибута высоты')
            self.dem_to_vector_dialog.progressBar.setValue(60)

            input_vector = set_z_from_raster(input_raster,input_vector, True)
            self.dem_to_vector_dialog.progressBar.setFormat('%p% Сохранение')
            self.dem_to_vector_dialog.progressBar.setValue(90)
            if expFolder != "":
                export_dxf(input_vector,expFolder)
                self.dem_to_vector_dialog.outputText.append(f'Слой <b>{input_vector.name()}</b> сохранен в файл <b>{expFolder}</b>')  # Добавляет строку с переносом
        except Exception as e:
            self.dem_to_vector_dialog.outputText.append(f'{datetime.now().strftime("%d/%m/%Y, %H:%M:%S")} Ошибка: {str(e)}')
        self.dem_to_vector_dialog.progressBar.setFormat('%p% Выполнено')
        self.dem_to_vector_dialog.progressBar.setValue(100)
        self.dem_to_vector_dialog.outputText.append(f'<b><font color="red">{datetime.now().strftime("%d/%m/%Y, %H:%M:%S")} Процесс завершен.</font></b>')  # Добавляет строку с переносом
        self.clean_memory()



    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginWebMenu(
                self.tr(u'&DEM to vector (DXF)'),
                action)
            self.iface.removeToolBarIcon(action)


    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start:
            self.first_start = False

        # show the dialog
        self.dem_to_vector_dialog.show()
        # Run the dialog event loop
        result = self.dem_to_vector_dialog.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            pass
